ktor:
  application:
    modules:
      - org.delcom.ApplicationKt.module
  deployment:
    port: ${APP_PORT}
    host: ${APP_HOST}

  database:
    host: ${DB_HOST}
    port: ${DB_PORT}
    name: ${DB_NAME}
    user: ${DB_USER}
    password: ${DB_PASSWORD}